#ifndef ULTIMATECOMPRESSOR_ARCHIVE_H
#define ULTIMATECOMPRESSOR_ARCHIVE_H

#include "macro.h"
#include "method.h"
#include "build.h"

#include <glib.h>

FOREACH_ARCHIVE(GENERATE_FUNC_NEW)
FOREACH_ARCHIVE(GENERATE_FUNC_IS_SUPPORTED)

#endif //ULTIMATECOMPRESSOR_ARCHIVE_H
