#ifndef ULTIMATECOMPRESSOR_ARCHIVE_H
#define ULTIMATECOMPRESSOR_ARCHIVE_H

#include "macro.h"
#include "method.h"
#include "build.h"

#include <glib.h>

/**
 * Implementation-dependant archive handle.
 */
typedef void* ArchiveHandle;

FOREACH_ARCHIVE(GENERATE_FUNC_NEW)
FOREACH_ARCHIVE(GENERATE_FUNC_OPEN)
FOREACH_ARCHIVE(GENERATE_FUNC_EXTRACT)
FOREACH_ARCHIVE(GENERATE_FUNC_WRITEFILE)
FOREACH_ARCHIVE(GENERATE_FUNC_CLOSE)
FOREACH_ARCHIVE(GENERATE_FUNC_IS_SUPPORTED)

#endif //ULTIMATECOMPRESSOR_ARCHIVE_H
