#ifndef ULTIMATECOMPRESSOR_ARCHIVE_H
#define ULTIMATECOMPRESSOR_ARCHIVE_H

#include "macro.h"
#include "method.h"

#include <glib.h>

FOREACH_ARCHIVE(GENERATE_FUNC)

#endif //ULTIMATECOMPRESSOR_ARCHIVE_H
